name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
          - black
          - ruff
          - mypy
          - isort
    env:
      TOXENV: ${{ matrix.toxenv }}
    
    name: "Tox ${{ matrix.toxenv }}"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Requirements [${{ matrix.toxenv }}]
        run: |
          pip install uv
          uv pip install ruff --system

      - name: Tox-${{ matrix.toxenv }}
        run: uv tool run tox
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
          - py38
          - py39
          - py310
          - py311
          - py312
        include:
          - toxenv: py38
            python-version: '3.8'
          - toxenv: py39
            python-version: '3.9'
          - toxenv: py310
            python-version: '3.10'
          - toxenv: py311
            python-version: '3.11'
          - toxenv: py312
            python-version: '3.12'
    env:
      TOXENV: ${{ matrix.toxenv }}
    name: "Python ${{ matrix.python-version }} | Tox ${{ matrix.toxenv }}"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements [Python-${{ matrix.python-version }}]
        run: |
          pip install uv
          uv pip install ruff --system

      - name: Tox-${{ matrix.toxenv }}
        run: uv tool run tox

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build Package
        run: |
          pip install uv
          uv tool run pdm build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          print-hash: true
          verbose: true
